name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: node v14.15.4
        uses: actions/setup-node@v1
        with:
          node-version: '14.15.4'
      - name: Install packages
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
      - name: Test (development)
        run: yarn test:dev
      - name: Test (minified)
        run: yarn test:minified
      - name: Test (development, JSX runtime)
        run: yarn test:jsx:dev
      - name: Test (minified, JSX runtime)
        run: yarn test:jsx:minified
